<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="11.3.1" />
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.9" />
      <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.17" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.17" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.17" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\CouponUsage\Implementations\" />
      <Folder Include="Features\DummyData\" />
      <Folder Include="Features\IdempotencyKey\enum\" />
      <Folder Include="Features\IdempotencyKey\Validators\" />
    </ItemGroup>

</Project>
